doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host_dev%'
        port: '%database_port_dev%'
        dbname: '%database_name_dev%'
        user: '%database_user_dev%'
        password: '%database_password_dev%'
