# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#        arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
parameters:
    #parameter_name: value

services:
    id_generator:
        class: AppBundle\Service\IdGenerator\IdGenerator

    # Repositories
    counter_card.card_repository:
        class: AppBundle\Entity\Repository\CardRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Card']
