# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#        arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
parameters:
    #parameter_name: value

services:
    id_generator:
        class: AppBundle\Service\IdGenerator\IdGenerator
    counter_card.user_registrator:
        class: AppBundle\Service\Security\UserRegistrator
        arguments: ['@counter_card.user_repository', '@id_generator']
    token_authenticator:
        class: AppBundle\Service\Security\TokenAuthenticator
        arguments: ['@counter_card.user_repository']

    # Repositories
    counter_card.user_repository:
        class: AppBundle\Entity\Repository\UserRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\User']
    counter_card.card_repository:
        class: AppBundle\Entity\Repository\CardRepository
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments: ['AppBundle\Entity\Card']

    # Event listeners
    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
